name: selenium_test
on: [ push, pull_request ]

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  selenium_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'

      - name: Update repo
        run: sudo apt-get update
      - name: Install software
        run: sudo apt-get install -y chromium-browser
      - name: Check Chromium version
        run: chromium-browser --version
      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: deployer/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/pr-deployer.yml') }}
      - name: Install dependencies
        run: poetry install
      - name: Run pytest
        run: poetry run pytest
      - name: Run the pytest and generate junit xml report
        run: poetry run pytest --junitxml report.xml
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "report.xml"